### ISSUE TITLE
Never trust user input

### ISSUE THREAD

**Issue by danmarsden** [schulportalhessen/moodle-report_sphorphanedfiles#3]
direct access to $_POST/$_GET/$_REQUEST is not allowed - please use moodle optional/required_param apis with appropriate PARAM_XXXX for cleaning the variables before use.

https://github.com/schulportalhessen/moodle-report_sphorphanedfiles/blob/releases/deleteResult.php#L10

that file also contains hard-coded german lang strings, and performs no security checks. Please ensure you read and understand:
https://docs.moodle.org/dev/Security#Summary_of_the_guidelines

**Comment by schulportalhessen** [comment]
The file https://github.com/schulportalhessen/moodle-report_sphorphanedfiles/blob/releases/deleteResult.php is not in use. I will delete it with the next release.

POST is used in mustache-template (https://github.com/schulportalhessen/moodle-report_sphorphanedfiles/blob/releases/templates/sectionTable.mustache)

and https://github.com/schulportalhessen/moodle-report_sphorphanedfiles/blob/releases/classes/View/OrphanedView.php

I will have a look at this issue soon. 
#1, #3, #4, #5, #6, #7 are already solved and will be uploaded soon

**Comment by andreasschenkel** [comment]
The file https://github.com/schulportalhessen/moodle-report_sphorphanedfiles/blob/releases/deleteResult.php is not in use. I will delete it with the next release.

POST is used in mustache-template (https://github.com/schulportalhessen/moodle-report_sphorphanedfiles/blob/releases/templates/sectionTable.mustache)

and https://github.com/schulportalhessen/moodle-report_sphorphanedfiles/blob/releases/classes/View/OrphanedView.php

I will have a look at this issue soon.
#1, #3, #4, #5, #6, #7 are already solved and will be uploaded soon

**Comment by danmarsden** [comment]
the mustache file is fine - that's not accessing the PHP un-filtered globals ($_POST/$_GET/$_REQUEST) posted by a user.

the orphanedfile one isn't quite right though - you take the raw $_POST value and trust it blindly and do not perform any sanity checks on the provided data.

the security checks are also a bit weird, I think if you removed a lot of the abstraction you have in these classes we'll find that there are few security issues around the access to the files too.

If I were you - I'd rip out all this extra abstraction you've got and just write some simple basic functions that read the data from the post using optional/required_param style fuctions to validate the data correctly - making sure contextid is an integer etc

and... ideally take a closer look at other Moodle code that shows you how to deal with stored files a bit better.

**Comment by andreasschenkel** [comment]
Version 2.0.0 User required parameter in post.

**Comment by schulportalhessen** [comment]
fixed with version [v2.0.0](https://github.com/schulportalhessen/moodle-report_sphorphanedfiles/releases/tag/v2.0.0)

**Comment by schulportalhessen** [comment]
fixed with version [v2.0.0](https://github.com/schulportalhessen/moodle-report_sphorphanedfiles/releases/tag/v2.0.0)
