### ISSUE TITLE
Link to report is missing in moodle 4

### ISSUE THREAD

**Issue by andreasschenkel** [schulportalhessen/moodle-report_sphorphanedfiles#8]
… will add something like the following Code

// Adds a link into the menu where all reports of a course can be accessed.
$navigation->add(get_string('pluginname', 'report_sphorphanedfiles'), $url, navigation_node::TYPE_SETTING, null, null, new pix_icon('i/report', ''));

**Comment by schulportalhessen** [comment]
fixed with release2.0.4 https://github.com/schulportalhessen/moodle-report_sphorphanedfiles/releases/tag/v2.0.4
